## User Settings

# Logging configuration: normal or verbose.
logging: normal

# Sets the local time zone.
time_zone: "Europe/Berlin"

# PV data grabber configuration
# Currently the following devices are available
#  - Dummy: a simple dummy devices that can be used for testing
#  - Fronius: supports Fronius Symo/GEN24 inverters + smar meter
#  - GoodweDNS: supports Goodwe DNS series inverters
#  - HomeWizardP1: supports HomeWizard Wi-Fi P1 meter
# Please configure a device which measures PV production as 'device:'
device:
  type:        Dummy       # Name of the device to load (must match an existing device .py file/class)
  start_date:  2020-08-01  # The start of operation (YYYY-MM-DD)
  host_name:   192.168.178.200  # Host name/IP address of the end point

device2:
  type:        None       # Name of the device to load (must match an existing device .py file/class)
  start_date:  2020-01-01  # The start of operation (YYYY-MM-DD)
  host_name:   192.168.178.200  # Host name/IP address of the end point

device3:
  type:        None       # Name of the device to load (must match an existing device .py file/class)
  start_date:  2020-01-01  # The start of operation (YYYY-MM-DD)
  host_name:   192.168.178.200  # Host name/IP address of the end point

device4:
  type:        None       # Name of the device to load (must match an existing device .py file/class)
  start_date:  2020-01-01  # The start of operation (YYYY-MM-DD)
  host_name:   192.168.178.200  # Host name/IP address of the end point

device5:
  type:        None       # Name of the device to load (must match an existing device .py file/class)
  start_date:  2020-01-01  # The start of operation (YYYY-MM-DD)
  host_name:   192.168.178.200  # Host name/IP address of the end point

# Device specific settings. These depend on the selected device adapter
fronius:
  specific_option: None  # allows for further passing of options, currently not used

goodwe_dns:
  specific_option: None  # allows for further passing of options, currently not used

homewizardp1:
  specific_option: None  # allows for further passing of options, currently not used

# Electricity prices. Used to calculate earnings in the UI.
prices:
  price_per_grid_kwh:     0.325  # Price for 1 kWh from the grid in Euro
  revenue_per_fed_in_kwh: 0.085  # Revenue for one fed in kWh in Euro


## Internal Settings. Do not modify!

# Web server configuration. Do not modify!
server:
  ip:     0.0.0.0       # IP address of the server, usually 0.0.0.0 should work
  port:   5000          # Port for the web server (default)

# Data grabber configuration. Do not modify!
grabber:
  interval_s: 5  # Interval for the data acquisition in seconds